### ISSUE TITLE
Recipes requiring sulfur aren't using forge/dusts_sulfur

### ISSUE THREAD

**Issue by sandalle** [aurilisdev/Ballistix#1]
Hey there, thank you for working on this (and the other Voltz-like mods)! :)

Just installed Ballistix-1.16.5-0.0.1-0 (already had electrodynamics), and saw that some recipes (e.g. Debilitation Explosive and Repulsive Explosive) require `electrodynamics:dustsulfur` only (which is also registered as `forge:dusts/sulfur`) and cannot use any other `forge:dusts/sulfur` (e.g. `mekanism:dust_sulfur` or `immersiveengineering:dust_sulfur`).

**Comment by aurilisdev** [comment]
This was fixed earlier today

**Comment by sandalle** [comment]
Awesome, thanks! :) Sorry, was using the latest version the Curse client gave me and didn't see a commit fixing this (https://github.com/aurilisdev/Ballistix/commit/0d259812b54ee8f9f2caa01ddc8115c4fc94108c is the closest I found and that sets them to `electrodynamics:dustsulfur` instead of `forge:dusts/sulfur`).

Was just about to open an issue for https://github.com/aurilisdev/Ballistix/commit/c1878af130c2841ef5f854556c80d472024b6785 , but you've already fixed that. ;)
