### ISSUE TITLE
Suggestion: Sounds for all explosions

### ISSUE THREAD

**Issue by ghost** [aurilisdev/Ballistix#15]
I feel like adding sounds for all the explosions would really complete the mod and make it a lot more enjoyable.

The first three grenades (condensive, attractive, and repulsive) have sounds for their explosions. All grenades have a fuse sound. However, the remaining four grenades do not have an explosion sound.

It is similar for the explosives, the obsidian, condensive, attractive, repulsive, and breaching have explosion sounds, but all other explosives have no explosion sound effect.

I also think there should be a sound effect for when a missile launches from the silo or rocket launcher.

Thanks for considering this suggsetion. I appreciate the work you've done to develop the mod it brings back lots of memories of playing the Voltz mod pack so many years ago!

**Comment by aurilisdev** [comment]
Will be done
