### ISSUE TITLE
missiles are gone after leaving and joining world?

### ISSUE THREAD

**Issue by epicyeeto** [aurilisdev/Ballistix#28]
i have your mod in my modpack and every time I leave and comeback to my world the missiles are gone

**Comment by aurilisdev** [comment]
Gone from what? In what situation?

**Comment by epicyeeto** [comment]
so when I place the missile in the silo and then I leave and then join back into the world it is gone like completely gone not even in the silo also I was in creative if that changes something

**Comment by ShadowFox88** [comment]
This also happens when reloading the chunks I think. the workaround I used was to forceload the chunks however every time the server restarts the missiles and explosives are gone.

**Comment by aurilisdev** [comment]
I will look into this and fix it if i can :)
