### ISSUE TITLE
Crash at the start of the game

### ISSUE THREAD

**Issue by WebmasterAnonymail** [aurilisdev/Ballistix#39]
The game window open, freeze, and close. The log file is this : 
[crash-2023-05-07_18.10.55-client.txt](https://github.com/aurilisdev/Ballistix/files/11415461/crash-2023-05-07_18.10.55-client.txt)

**Comment by skiprocks999** [comment]
You are on a very old version of electrodynamics. Update to a later version

**Comment by WebmasterAnonymail** [comment]
1 month and half is not very old but now this work so thank
