### ISSUE TITLE
Nuclear Explosive keep infinitely exploding without Nuclear Science mod installed

### ISSUE THREAD

**Issue by Anktratten** [aurilisdev/Ballistix#43]
Using Ballistix 1.16.5-0.3.0-0.jar

Without the nuclear science mod installed, the nuclear explosive keeps on exploding forever and does damage to entities around it.

**Comment by aurilisdev** [comment]
1.16 is no longer supported

**Comment by aurilisdev** [comment]
This has been fixed for newer versions by me just now though :)
