### ISSUE TITLE
1.18.2 missle silo doesn't work

### ISSUE THREAD

**Issue by Siqust** [aurilisdev/Ballistix#45]
I tried to use missile silo with redstone and distant launch but neither of them worked(I tried last and pre-last 1.18.2 version) (Is 1.18.2 supported yet?)

**Comment by skiprocks999** [comment]
This will be hopefully be addressed soon in a bug fix update. Inform us if there are still issues afterwards.

**Comment by skiprocks999** [comment]
This has been fixed with the latest release
