### ISSUE TITLE
Game crashes when thermobaric explosion

### ISSUE THREAD

**Issue by ghost** [aurilisdev/Ballistix#5]
Steps
Click thermbaric explosive block with flint and steel and watch and wait for it to explode, game freezes then crashes

Java 1.8.0-271
Forge 36.1.16

Only six mods present:
Ballistix 1.16.5 - 0.2.0-0
Electrodynamics 1.16.5 - 0.4.0-0
Nuclear Science 1.16.5 - 0.3.0-0
JEI - 1.16.5 - 7.7.0.98
OptiFine 1.16.5 G8
Gamemode Overhaul 1.16.4 - 1.4.2.4

I also tried with and without optifine. Same crash.

Crash log attached
[crash-2021-05-20_15.56.55-server.txt](https://github.com/aurilisdev/Ballistix/files/6518955/crash-2021-05-20_15.56.55-server.txt)

**Comment by aurilisdev** [comment]
Has been fixed
