### ISSUE TITLE
(the latest update for 1.16.5) - antimatter explosives destroys only sand and kill mobs. sometimes when they lunches from rockets, they crashes world

### ISSUE THREAD

**Issue by D1xeRs** [aurilisdev/Ballistix#68]
the game crash with other mods more often 
[logs.txt](https://github.com/user-attachments/files/17036684/logs.txt)

**Comment by D1xeRs** [comment]
[crash-2024-10-03_03.42.47-server.txt](https://github.com/user-attachments/files/17237731/crash-2024-10-03_03.42.47-server.txt)
only ballistix and electrodynamic

**Comment by skiprocks999** [comment]
Have you encountered this issue in later versions of Electrodynamics & Ballistix?

**Comment by D1xeRs** [comment]
No, only latest 1.16.5 , tested it on latest for 1.20 and there all working normal

**Comment by skiprocks999** [comment]
Unfortunately 1.16.5 is unsupported at this time. If we have critical issues with the mod arise we might consider a fix. You are welcome to submit a PR with the fix yourself if you like.
